version: '3.8'

services:
  master:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: replica
      MYSQL_REPLICATION_PASSWORD: xx
    volumes:
      - master_data:/var/lib/mysql
      - ./configs/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./scripts/fixture.sql:/scripts/fixture.sql
      - ./scripts/master_setup.sh:/scripts/master_setup.sh
      - ./scripts/set_permissions_master_cnf.sh:/scripts/set_permissions_master_cnf.sh
    command: ["bash", "-c", "/scripts/set_permissions_master_cnf.sh && /scripts/master_setup.sh && mysqld"]
    ports:
      - "3306:3306"
    networks:
      - mysql_network

  slave:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_REPLICATION_MASTER_HOST: master
      MYSQL_REPLICATION_USER: replica
      MYSQL_REPLICATION_PASSWORD: xx
    ports:
      - "3307:3306"
    depends_on:
      - master
    volumes:
      - slave_data:/var/lib/mysql
      - ./configs/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ./scripts/slave_setup.sh:/scripts/slave_setup.sh
      - ./scripts/set_permissions_slave_cnf.sh:/scripts/set_permissions_slave_cnf.sh
    command: ["bash", "-c", "/scripts/set_permissions_slave_cnf.sh && /scripts/slave_setup.sh && mysqld"]
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge

volumes:
  master_data:
  slave_data: